#组件信息
app: unicom
component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: main # (必填) 创建的实例名称，请修改成您的实例名称

#联通自动操作脚本
inputs:
  name: ${app}-Task #函数名称
  #namespace: unicom
  src: ./  #代码路径
  handler: main.main #入口
  runtime: Python3.6 # 云函数运行时的环境
  region: ap-guangzhou # 云函数所在区域
  description: '联通营业厅任务脚本'
  timeout: 900
  events: # 触发器
    - timer: # 定时触发器
        name: timer-${name} #触发器名称，默认timer-${name}-${stage}
        parameters:
          cronExpression: '0 30 6 * * * *' #7:30
          enable: true